# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :execFile do
    Dir.chdir ".." do
      sh "touch bundle-js.txt"
    end
  end

  desc "Submit to Crashlytics"
  lane :appBeta do

    gradle(task: 'incrementVersionCode') # //, project_dir: '../../android/'

    #gradle(task: "clean assembleRelease")
    gradle(task: "clean assembleDebug")

    crashlytics(
      api_token: '0d9daa925e70ebb25ff2379f448b094463017780',
      build_secret: 'ead24b0e393bd41ef55897fed0978530c4140107c1afcce05a47d25369435019',
      notes_path: '../../src/Readme.md'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
